name: Keep Supabase Project Awake

on:
  schedule:
    - cron: "0 7 * * *"  # Daily at 7:00 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send keep-alive ping to Supabase
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" "${{ secrets.SUPABASE_URL }}/rest/v1/colors" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
